#
# Copyright (c) 2018-2023 Red Hat, Inc.
#    This program and the accompanying materials are made
#    available under the terms of the Eclipse Public License 2.0
#    which is available at https://www.eclipse.org/legal/epl-2.0/
#
#  SPDX-License-Identifier: EPL-2.0
#
#  Contributors:
#    Red Hat, Inc. - initial API and implementation
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: devspaces-plugin-registry
objects:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: devspaces
        component: plugin-registry
      name: plugin-registry
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: devspaces
          component: plugin-registry
      strategy:
        type: RollingUpdate
        rollingUpdate:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
      template:
        metadata:
          labels:
            app: devspaces
            component: plugin-registry
        spec:
          containers:
            - image: ${IMAGE}:${IMAGE_TAG}
              imagePullPolicy: ${PULL_POLICY}
              name: plugin-registry
              ports:
                - containerPort: 8080
              livenessProbe:
                httpGet:
                  path: /v3/plugins/
                  port: 8080
                initialDelaySeconds: 30
                periodSeconds: 10
                timeoutSeconds: 3
                successThreshold: 1
                failureThreshold: 10
              readinessProbe:
                httpGet:
                  path: /v3/plugins/
                  port: 8080
                initialDelaySeconds: 3
                periodSeconds: 10
                timeoutSeconds: 3
                successThreshold: 1
                failureThreshold: 10
              resources:
                requests:
                  cpu: 100m
                  memory: 512Mi
                limits:
                  cpu: 500m
                  memory: ${MEMORY_LIMIT}
              envFrom:
                - configMapRef:
                    name: plugin-registry
                    optional: true
      triggers:
        - type: ConfigChange
  - apiVersion: v1
    kind: Service
    metadata:
      name: plugin-registry
    spec:
      ports:
        - name: http
          protocol: TCP
          port: 8080
          targetPort: 8080
      selector:
        app: devspaces
        component: plugin-registry
  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: devspaces
        component: plugin-registry
      name: plugin-registry
    spec:
      to:
        kind: Service
        name: plugin-registry
        weight: 100
      port:
        targetPort: 8080
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: plugin-registry
    data:
      START_OPENVSX: ${START_OPENVSX}
parameters:
  - name: IMAGE
    value: registry.redhat.io/devspaces/pluginregistry-rhel8
    displayName: Red Hat OpenShift Dev Spaces plugin registry image
    description: Red Hat OpenShift Dev Spaces plugin registry container image. Defaults
      to registry.redhat.io/devspaces/pluginregistry-rhel8
  - name: IMAGE_TAG
    value: '3.10'
    displayName: Red Hat OpenShift Dev Spaces plugin registry version
    description: Red Hat OpenShift Dev Spaces plugin registry version
  - name: MEMORY_LIMIT
    value: 1024Mi
    displayName: Memory Limit
    description: Maximum amount of memory the container can use. Defaults 256Mi
  - name: PULL_POLICY
    value: Always
    displayName: Red Hat OpenShift Dev Spaces plugin registry image pull policy
    description: Always pull by default. Can be IfNotPresent
  - name: START_OPENVSX
    value: 'false'
    displayName: Start embedded OpenVSX registry
    description: If true, an embedded OpenVSX registry will be started
