#
# Copyright (c) 2020-2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: Plugin Registry - PR check - shellcheck
# for now, this is enabled only for the plugin registry as numeous other scripts in /product/ folder fail shellcheck. 
# TODO: enable this for the whole project once shellcheck complaints have been cleaned up
on: 
  push:
    paths:
    - 'dependencies/che-plugin-registry/**'
  pull_request:
    paths:
    - 'dependencies/che-plugin-registry/**'

jobs:
  check:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: dependencies/che-plugin-registry
    steps:
    - name: Clone source code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: ShellCheck
      run: |
        find . -type f -name "*.sh" | xargs shellcheck --external-sources
