#
# Copyright (c) 2020-2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: Plugin Registry - PR check - typescript

on:
  pull_request:
    paths:
    - 'dependencies/che-plugin-registry/**/package.json'
    - 'dependencies/che-plugin-registry/tools/**/*.ts'
    - '.github/workflows/plugin-registry-pr-check-typescript.yml'
  push:
    paths:
    - 'dependencies/che-plugin-registry/**/package.json'
    - 'dependencies/che-plugin-registry/tools/**/*.ts'
    - '.github/workflows/plugin-registry-pr-check-typescript.yml'

jobs:
  check:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: dependencies/che-plugin-registry
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: Clone source code
      uses: actions/checkout@v2
      with:
        fetch-depth: 10
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - uses: actions/cache@v2
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: yarn-
    - name: typescript
      run: |
        yarn
        yarn workspaces run build
    - name: report-coverage
      uses: codecov/codecov-action@v1
      with:
        files: ./tools/pr-check/coverage/coverage-final.json,./tools/automation/coverage/coverage-final.json,./tools/build/coverage/coverage-final.json
